### ISSUE TITLE
Process finished with exit code 0 when running in webstorm

### ISSUE THREAD

**Issue by QuantumInformation** [wallabyjs/wallaby-create-react-app-ts#2]
I used this configuration, but when running in webstorm, I always get this

/Users/nikos/.nvm/versions/node/v10.15.1/bin/node ... /web-client/wallaby.js"

Process finished with exit code 0

<img width="1008" alt="Screenshot 2019-03-25 at 12 22 57" src="https://user-images.githubusercontent.com/216566/54920335-e1e23680-4efa-11e9-96b3-431635f6dc97.png">

**Comment by smcenlly** [comment]
In your screenshot, you've created a Node.js run configuration. To run wallaby, you will need to create a Wallaby run configuration.

![image](https://user-images.githubusercontent.com/2074089/54958583-f6c5d500-4fa1-11e9-8f95-ae8acbfa6caa.png)

Once you've created a new configuration, the only parameter you should have to apply is your Wallaby.js configuration file (see below).

![image](https://user-images.githubusercontent.com/2074089/54958614-13faa380-4fa2-11e9-9260-ded4bae5fee7.png)

You can read more about getting started with JetBrains IDEs and how to configure Wallaby in [our docs](https://wallabyjs.com/docs/intro/get-started-jetbrains.html#run-configuration).
