### ISSUE TITLE
describe is not defined  vscode

### ISSUE THREAD

**Issue by jsvanilla** [wallabyjs/wallaby-create-react-app-ts#26]
I have a problem running a typescript create-react-app template.  The test file run normally in the terminal but it doesn´t work when i start to use wallaby

<img width="425" alt="Captura de Pantalla 2021-09-26 a la(s) 5 28 41" src="https://user-images.githubusercontent.com/36719905/134804032-78e604f8-1542-49ca-8214-2a594af1f8ff.png">

<img width="1179" alt="Captura de Pantalla 2021-09-26 a la(s) 5 30 46" src="https://user-images.githubusercontent.com/36719905/134804110-508bb72a-1c05-4c35-8211-9902621f47c1.png">

**Comment by ArtemGovorov** [comment]
@jsvanilla Can you please create an issue here at https://github.com/wallabyjs/public/issues/new and share your Wallaby Diagnostics Report as described in the issue template?
