### ISSUE TITLE
Update to 3.0

### ISSUE THREAD

**Issue by sjetha-pason** [wallabyjs/wallaby-create-react-app-ts#4]
I just upgraded this demo to CRA 3, and the wallaby testing in VS Code stopped working. Could this be updated to run correctly for CRA 3-based projects, please?

Many thanks all your work.

**Comment by smcenlly** [comment]
We've updated the sample to use the latest CRA (3.0.1) as well as all 3.0.1 dependencies. Everything seems to be working for us. We've tested on two separate machines using both `npm` and `yarn` to install dependencies.

We also created a new react app from scratch using:

```
create-react-app my-ts-app-cr3-ts --typescript
```

I then added the same `wallaby.js` configuration from the sample and everything is working.

---

If the demo still isn't working for you, could you please clone to a fresh directory and reinstall all modules and try again? If that doesn't fix it for you, could please provide details of what's not working?
